### ISSUE TITLE
Please help

### ISSUE THREAD

**Issue by Lioncel888** [gschurck/tradoge#15]
_________                    ______       ___       ______    ________
|  _   _  |                  |_   _ `.   .'   `.   .' ___  |  |_   __  |
|_/ | | \_|  _ .--.   ,--.     | | `. \ /  .-.  \ / .'   \_|    | |_ \_|
    | |     [ `/'`\] `'_\ :    | |  | | | |   | | | |   ____    |  _| _
   _| |_     | |     // | |,  _| |_.' / \  `-'  / \ `.___]  |  _| |__/ |
  |_____|   [___]    \'-;__/ |______.'   `.___.'   `._____.'  |________|

TraDOGE is up to date : v1.2.2

Traceback (most recent call last):
  File "C:\Users\qinzh\tradoge\tradoge.py", line 543, in <module>
    main()
  File "C:\Users\qinzh\tradoge\tradoge.py", line 421, in main
    menu(config_obj, client)
  File "C:\Users\qinzh\tradoge\tradoge.py", line 188, in menu
    doge_balance = client.get_asset_balance(asset='DOGE')['free']
  File "C:\Users\qinzh\AppData\Local\Programs\Python\Python39\lib\site-packages\binance\client.py", line 1792, in get_asset_balance
    res = self.get_account(**params)
  File "C:\Users\qinzh\AppData\Local\Programs\Python\Python39\lib\site-packages\binance\client.py", line 1767, in get_account
    return self._get('account', True, data=params)
  File "C:\Users\qinzh\AppData\Local\Programs\Python\Python39\lib\site-packages\binance\client.py", line 237, in _get
    return self._request_api('get', path, signed, version, **kwargs)
  File "C:\Users\qinzh\AppData\Local\Programs\Python\Python39\lib\site-packages\binance\client.py", line 202, in _request_api
    return self._request(method, uri, signed, **kwargs)
  File "C:\Users\qinzh\AppData\Local\Programs\Python\Python39\lib\site-packages\binance\client.py", line 197, in _request
    return self._handle_response()
  File "C:\Users\qinzh\AppData\Local\Programs\Python\Python39\lib\site-packages\binance\client.py", line 230, in _handle_response
    raise BinanceAPIException(self.response)
binance.exceptions.BinanceAPIException: APIError(code=-1021): Timestamp for this request was 1000ms ahead of the server's time.

**Comment by Lioncel888** [comment]
The problem is solved, windows time didn't sync. thanks
