### ISSUE TITLE
Receiving an error in the Windows version

### ISSUE THREAD

**Issue by donmega** [gschurck/tradoge#22]
After configuring the bot i receive this error every time i start the bot:
Your Binance API keys are present in config file
? Enter your password to decrypt your Binance API keys  **********
Traceback (most recent call last):
  File "tradoge.py", line 594, in <module>
  File "tradoge.py", line 468, in main
  File "tradoge.py", line 376, in login
  File "binance\client.py", line 1999, in get_system_status
  File "binance\client.py", line 270, in _request_withdraw_api
  File "binance\client.py", line 260, in _request
  File "binance\client.py", line 313, in _handle_response
binance.exceptions.BinanceAPIException: APIError(code=0): Invalid JSON error message from Binance: This endpoint has been deprecated, please integrate with “GET@/sapi/v1/system/status”. See details in the announcement: https://www.binance.com/en/support/announcement/f45dde7da58b473aa885349946bed269
[16932] Failed to execute script tradoge

I am running the newest version (1.3.2)

**Comment by gschurck** [comment]
Ok it seams like Binance disabled some parts of the API... -_-
I have the same issue, I will have to push an update asap becauses now the whole bot is broken.
Thanks.

**Comment by gschurck** [comment]
Updated dependencies, everything should be working again now :)
-> https://github.com/gschurck/tradoge/releases/tag/v1.3.3
