### ISSUE TITLE
New error !

### ISSUE THREAD

**Issue by BROUETTE10** [gschurck/tradoge#9]
Eyo man, thank you for creating this, it's a gem.

Got an error since yesterday, it was fine for a week but the next day i got a weird error i can't pass on, here's the error : 

TraDOGE is up to date : v1.2.2

Traceback (most recent call last):
  File "tradoge.py", line 543, in <module>
    main()
  File "tradoge.py", line 421, in main
    menu(config_obj, client)
  File "tradoge.py", line 188, in menu
    doge_balance = client.get_asset_balance(asset='DOGE')['free']
  File "binance\client.py", line 1792, in get_asset_balance
  File "binance\client.py", line 1767, in get_account
  File "binance\client.py", line 237, in _get
  File "binance\client.py", line 202, in _request_api
  File "binance\client.py", line 197, in _request
  File "binance\client.py", line 230, in _handle_response
binance.exceptions.BinanceAPIException: APIError(code=-1021): Timestamp for this request was 1000ms ahead of the server's time.

I got a very good connection but you can read what it says, i found it weird and tried to search for the answer, but without responses.

Thank's for giving me a little of your time !

**Comment by gschurck** [comment]
Hey, thanks !
This issue should be due to your computer time, which is not correctly synced.
If you are on Windows try to sync your time in the settings.

**Comment by BROUETTE10** [comment]
Thank's for the fast answer !

I've restarded my computer and it worked, maybe it was ON for too long... sorry for the little disturb, it was effectively a problem with my time.
